#!/usr/bin/env nix-shell
#! nix-shell --pure -i bash -I nixpkgs=/home/developer/nodejs/node/tools/nix/pkgs.nix /home/developer/nodejs/node/shell.nix

set -xe

make install PREFIX=/home/developer/.local -C /home/developer/nodejs/node
{
    echo ''
    # Expose the PATH generated by Nix + the recently built `node` installation
    echo "export PATH=/home/developer/.local/bin:$PATH"
 } >> /home/developer/.bashrc
