#!/usr/bin/env bash

set -xe

cd /home/developer/nodejs/node
eval "$(direnv export bash)"

make install PREFIX=/home/developer/.local -C /home/developer/nodejs/node
{
    echo ''
    # Expose the PATH generated by Nix + the recently built `node` installation
    echo "export PATH=/home/developer/.local/bin:$PATH"
 } >> /home/developer/.bashrc
