name: Build and Publish Linux AMD64 Image

on:
  workflow_dispatch: # allows us to trigger runs manually in the GitHub UI
  schedule:
    - cron:  '0 0 * * *' # runs nightly

jobs:
  docker:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with: # these are defined in the GitHub Secrets UI
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: nodejs/devcontainer:nightly-linux-amd64
